{{- if .Values.backupper.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.fullname" . }}-backupper
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: backupper
    {{- include "chart.labels" $ | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backupper.accesskey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backupper.secretkey | b64enc }}
  BUCKET: {{ .Values.backupper.bucketname | b64enc}}
  REGION: {{ .Values.backupper.region | b64enc}}
{{- end }}