apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    servicemonitor: "true"
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8011
    name: timebase
  selector:
    app.kubernetes.io/component: server
    {{- include "chart.matchLabels" $ | nindent 4 }}
