apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web-admin
    servicemonitor: "true"
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  ports:
  - port: 8099
    name: timebase-admin
  selector:
    app.kubernetes.io/component: web-admin
    {{- include "chart.matchLabels" $ | nindent 4 }}