apiVersion: v1
appVersion: 6.1.1
description: A Helm chart for Timebase server
home: https://timebase.info
icon: https://raw.githubusercontent.com/epam/TimeBaseHelm/master/assets/icon.svg
maintainers:
- email: Aliaksei_Banshchyk@epam.com
  name: Aliaksei Banshchyk
name: timebase
sources:
- https://github.com/epam/TimeBase-CE
- https://github.com/epam/TimebaseWS
- https://github.com/epam/TimeBaseTimescaleConnector
- https://github.com/epam/TimeBaseClickhouseConnector
- https://github.com/epam/TimeBaseKafkaConnector
version: 0.6.1
